#!/bin/bash

# Run this file inside an Ubuntu Bionic Docker image

#Set architecture: amd64, i386
ARCH=$1

set -e # Halt on error
set -x # Be verbose

# Fetch dependencies for Qt compilation
echo "fetching dependencies for arch: $ARCH"

# General dependencies
apt-get update
apt-get install -y \
  pkg-config \
  apt-utils \
  bison \
  build-essential \
  cmake \
  flex \
  g++ \
  git \
  gperf \
  p7zip-full \
  perl \
  python \
  ruby \
  wget

# Specific dependencies for Qt5
apt-get install -y \
    '^libxcb.*-dev'

apt-get install -y \
    flite1-dev
apt-get install -y \
    libatspi2.0-dev
apt-get install -y \
    libavcodec-dev
apt-get install -y \
    libcups2-dev
apt-get install -y \
    libfontconfig1-dev
apt-get install -y \
    libfreetype6-dev
apt-get install -y \
    libgtk-3-dev
apt-get install -y \
    libgl1-mesa-dev
apt-get install -y \
    libglu1-mesa-dev
apt-get install -y \
    libicu-dev
apt-get install -y \
    libspeechd-dev
apt-get install -y \
    libx11-dev
apt-get install -y \
    libx11-xcb-dev
apt-get install -y \
    libxext-dev
apt-get install -y \
    libxfixes-dev
apt-get install -y \
    libxi-dev
apt-get install -y \
    libxkbcommon-dev
apt-get install -y \
    libxkbcommon-x11-dev
apt-get install -y \
    libxrender-dev
apt-get install -y \
    libxslt-dev
apt-get install -y \
    speech-dispatcher


# Specific dependencies for Qt WebEngine
apt-get install -y \
    libasound2-dev \
    libcap-dev \
    libdbus-1-dev \
    libdrm-dev \
    libegl1-mesa-dev \
    libevent-dev \
    libnss3-dev \
    libpci-dev \
    libpulse-dev \
    libxcomposite-dev \
    libxcursor-dev \
    libxdamage-dev \
    libxrandr-dev \
    libxss-dev \
    libxtst-dev \
    libudev-dev \
    nodejs

# Specific dependencies for Qt Multimedia
apt-get install -y \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    libgstreamer-plugins-bad1.0-dev

# Specific dependencies for SSL support
apt-get install -y \
    libgcrypt11-dev \
    libssl1.1 \
    libssl-dev \
    openssl

# libxscrnsaver ??
# sudo apt-get install  libatkmm-1.6-dev libbz2-dev 
# libxcb-composite0 libxcb-cursor0 libxcb-damage0 libxcb-dpms0
# libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0
# libxcb-icccm4 libxcb-image0 libxcb-keysyms1 
# libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render-util0
# libxcb-render0 libxcb-res0 libxcb-screensaver0
# libxcb-shape0 libxcb-shm0 libxcb-sync1
# libxcb-util1 libxcb-xevie0 libxcb-xf86dri0 libxcb-xfixes0
# libxcb-xinerama0 libxcb-xkb1 libxcb-xprint0
# libxcb-xtest0 libxcb-xv0 libxcb-xvmc0 libxcb1


#    xkb-data:$ARCH \
#    libxkbcommon-x11-0:$ARCH \
#    libsndfile1-dev:$ARCH \
#    portaudio19-dev:$ARCH \
#    libportmidi-dev:$ARCH \
#    zlib1g-dev:$ARCH \
#    libmp3lame-dev:$ARCH \
#    libcups2:$ARCH \
#    libfontconfig1:$ARCH \
#    libwebp-dev:$ARCH \
#    libprotobuf-dev:$ARCH \
#    libjsoncpp-dev:$ARCH \
#    libsnappy-dev:$ARCH \
#    libvpx-dev:$ARCH \
#    libre2-dev:$ARCH \
#    libxslt1-dev:$ARCH \
#    alsa-tools:$ARCH \
#    alsa-utils:$ARCH \
#    libasound2-plugins:$ARCH \
#    pulseaudio:$ARCH \
#    liblcms2-2:$ARCH \
#    libmng1:$ARCH \
#    libpulse0:$ARCH \
#    libjson-c-dev:$ARCH \
#    libexpat1-dev:$ARCH \
#    libdbus-1-3:$ARCH \
#    libglib2.0-0:$ARCH \
#    libkeyutils-dev:$ARCH \
#    libwrap0:$ARCH \
#    libacl1:$ARCH \
#    libpcre3:$ARCH \
#    libgles2-mesa-dev:$ARCH \
#    libgles2-mesa:$ARCH \
#    libegl1-mesa:$ARCH \
#    at-spi2-core:$ARCH \
#    libxkbcommon0:$ARCH \
#    libopus0:$ARCH \
#    libopus-dev:$ARCH \
#    libopusfile0:$ARCH \
#    libopusfile-dev:$ARCH \
#    libpango1.0-dev:$ARCH \
#    x11proto-dev:$ARCH \
#    shared-mime-info:$ARCH \
#    libxau-dev:$ARCH \

apt-get clean

# Fetch KDE-patched Qt sources, compile and install it

git clone --branch kde/5.15 https://invent.kde.org/qt/qt/qt5.git qt5source
cd qt5source
git checkout kde/5.15
git submodule update --init --recursive


# Workaround for armhf case for Qt 5.x
if [ "$ARCH" == "armhf" ]
then
  cp -r qtbase/mkspecs/linux-arm-gnueabi-g++ qtbase/mkspecs/linux-arm-gnueabihf-g++
  sed -i 's/gnueabi/gnueabihf/g' qtbase/mkspecs/linux-arm-gnueabihf-g++/qmake.conf
fi

mkdir build
cd build

# Configure Qt
../configure -release -prefix /qt5 -opensource -confirm-license -platform linux-g++ -make examples \
-nomake tests -skip qt3d -skip qtcanvas3d -skip qtdatavis3d -skip qtdoc -skip qtdocgallery -skip qtgamepad \
-skip qtpurchasing -skip qtsensors -skip qtwebengine -cups -accessibility -opengl dynamic -gtk -pkg-config

# -opengl desktop ?

# make -j $(($(nproc)+1))
# make install -j $(($(nproc)+1))

echo 'Recipe1 completed'
