name: Linux

on:
  workflow_dispatch:
    inputs:
      build_architecture:
        description: 'Build for Linux architecture: amd64, i386'
        required: true
        default: 'amd64'

jobs:
  build_qt5:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Clone repository
      uses: actions/checkout@v3
    - name: setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Build Qt5
      run: |
        sudo mkdir /qt5
        chmod +x /home/runner/work/Qt5Binaries/Qt5Binaries/Recipe1
        sudo cp /home/runner/work/Qt5Binaries/Qt5Binaries/Recipe1 /qt5
        sudo docker run -i -v "/qt5:/qt5" "${{ github.event.inputs.build_architecture }}/ubuntu:bionic" /bin/bash /qt5/Recipe1 ${{ github.event.inputs.build_architecture }}
    - name: Upload artifacts on GitHub
      uses: actions/upload-artifact@v3
      with:
        name: "qt5linux_${{ github.event.inputs.build_architecture }}"
        path: /qt5      
