name: Prova

on:
  workflow_dispatch:

jobs:
  build_prova:
    runs-on: windows-2022
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Download source
      run: |
        Remove-Item -Path C:\Android -Force -Recurse
        Remove-Item -Path C:\SeleniumWebDrivers -Force -Recurse
        Remove-Item -Path C:\Miniconda -Force -Recurse
        Remove-Item -Path C:\Julia -Force -Recurse
        Remove-Item -Path C:\tools -Force -Recurse
        Remove-Item -Path C:\selenium -Force -Recurse
        Remove-Item -Path C:\vcpkg -Force -Recurse
        docker image prune --all --force
        choco install -y git.install
        choco install -y wget
        choco install -y 7zip.install
        choco install -y python2
        choco install -y openssl
        choco install -y ninja
        git clone --branch kde/5.15 https://invent.kde.org/qt/qt/qt5.git C:\qt5source
        cd C:\qt5source
        dir
        git checkout kde/5.15
    - name: Get jom
      shell: cmd
      run: |
        call "wget.exe" -q --show-progress --no-check-certificate "https://download.qt.io/official_releases/jom/jom_1_1_3.zip" -O jom_1_1_3.zip
        call "7z" x -y jom_1_1_3.zip -ojom
        del jom_1_1_3.zip
    - name: Set PATH
      shell: bash
      run: |
        echo "C:/qt5source/gnuwin32/bin" >> $GITHUB_PATH
        echo "D:/a/Qt5Binaries/Qt5Binaries/jom" >> $GITHUB_PATH
        echo "C:/Python27" >> $GITHUB_PATH
        echo "C:/Python27/Scripts" >> $GITHUB_PATH
    - name: Configure
      working-directory: C:\qt5source
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 10.0.19041.0
        dir
        dir ..
        C:\msys64\usr\bin\find.exe . -name .git -type d -exec C:\msys64\usr\bin\rm.exe -rf {} +
        mkdir build
        dir
        cd build
        dir ..\qtwebengine
    - name: Test
      shell: cmd
      working-directory: C:\qt5source\build
      run: |
        dir ..
